[package]
name = "martial"
version = "0.1.0"
edition = "2024"
rust-version = "1.96"

[dependencies]
c2pa = { version = "0.90.16", features = ["file_io", "add_thumbnails"] }
clap = { version = "4.6.6", features = ["derive", "color"] }
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }
infer = "0.22.0"
